version: '3'

services:
  nuxt:
    container_name: incident_nuxt
    image: node:16
    environment:
      - HOST=0.0.0.0
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./front:/app
    command: bash -c "cd /app && npm run dev"


  web:
    container_name: incident_web
    restart: on-failure
    build: ./back
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./back:/app
    command: python manage.py runserver 0.0.0.0:8000