# Generated by Django 3.2.3 on 2022-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
